export const UserActionTypes = {
  LOGIN_START: '@@user/LOGIN_START',
  LOGIN_SUCCESS: '@@user/LOGIN_SUCCESS',
  LOGIN_ERROR: '@@user/LOGIN_ERROR',

  FETCH_PROFILE_START: '@@user/FETCH_PROFILE_START',
  FETCH_PROFILE_SUCCESS: '@@user/FETCH_PROFILE_SUCCESS',
  FETCH_PROFILE_ERROR: '@@user/FETCH_PROFILE_ERROR',

  LOGOUT_START: '@@user/LOGOUT_START',
  LOGOUT_SUCCESS: '@@user/LOGOUT_SUCCESS',
  LOGOUT_ERROR: '@@user/LOGOUT_ERROR',

  FETCH_USER_INFERIORS_START: '@@user/FETCH_USER_INFERIORS_START',
  FETCH_USER_INFERIORS_SUCCESS: '@@user/FETCH_USER_INFERIORS_SUCCESS',
  FETCH_USER_INFERIORS_ERROR: '@@user/FETCH_USER_INFERIORS_ERROR',

  AUTHENTICATION_FAILED: '@@user/AUTHENTICATION_FAILED',
}

export const Geocode = {
  REGEOCODE_START: '@@geocode/REGEOCODE_START',
  REGEOCODE_SUCCESS: '@@geocode/REGEOCODE_SUCCESS',
  REGEOCODE_ERROR: '@@geocode/REGEOCODE_ERROR'
}

export const Draft = {
  VALUE_CHANGE: '@@draft/VALUE_CHANGE',

  CREATE_LOCAL: '@@draft/CREATE_LOCAL',

  REMOTE_UPDATE_START: '@@draft/REMOTE_UPDATE_START',
  REMOTE_UPDATE_SUCCESS: '@@draft/REMOTE_UPDATE_SUCCESS',
  REMOTE_UPDATE_ERROR: '@@draft/REMOTE_UPDATE_ERROR',
  
  REMOTE_CREATE_START: '@@draft/REMOTE_CREATE_START',
  REMOTE_CREATE_SUCCESS: '@@draft/REMOTE_CREATE_SUCCESS',
  REMOTE_CREATE_ERROR: '@@draft/REMOTE_CREATE_ERROR',
  
  LOCAL_SAVE_START: '@@draft/LOCAL_SAVE_START',
  LOCAL_SAVE_SUCCESS: '@@draft/LOCAL_SAVE_SUCCESS',
  LOCAL_SAVE_ERROR: '@@draft/LOCAL_SAVE_ERROR',

  LOCAL_REMOVE_START: '@@draft/LOCAL_REMOVE_START',
  LOCAL_REMOVE_SUCCESS: '@@draft/LOCAL_REMOVE_SUCCESS',
  LOCAL_REMOVE_ERROR: '@@draft/LOCAL_REMOVE_ERROR',
}

export const Task = {
  FETCH_USER_TASK_LIST_START: '@@task/FETCH_USER_TASK_LIST_START',
  FETCH_USER_TASK_LIST_SUCCESS: '@@task/FETCH_USER_TASK_LIST_SUCCESS',
  FETCH_USER_TASK_LIST_ERROR: '@@task/FETCH_USER_TASK_LIST_ERROR',

  DELTE_USER_TASK_START: '@@task/DELTE_USER_TASK_START',
  DELTE_USER_TASK_SUCCESS: '@@task/DELTE_USER_TASK_SUCCESS',
  DELTE_USER_TASK_ERROR: '@@task/DELTE_USER_TASK_ERROR',

  FETCH_TASK_START: '@@task/FETCH_TASK_START',
  FETCH_TASK_SUCCESS: '@@task/FETCH_TASK_SUCCESS',
  FETCH_TASK_ERROR: '@@task/FETCH_TASK_ERROR',

  FETCH_TASKS_START: '@@task/FETCH_TASKS_START',
  FETCH_TASKS_SUCCESS: '@@task/FETCH_TASKS_SUCCESS',
  FETCH_TASKS_ERROR: '@@task/FETCH_TASKS_ERROR',

  UPDATE_USER_TASK_START: '@@task/UPDATE_USER_TASK_START',
  UPDATE_USER_TASK_SUCCESS: '@@task/UPDATE_USER_TASK_SUCCESS',
  UPDATE_USER_TASK_ERROR: '@@task/UPDATE_USER_TASK_ERROR',

  FETCH_TASK_PDF_START: '@@task/FETCH_TASK_PDF_START',
  FETCH_TASK_PDF_SUCCESS: '@@task/FETCH_TASK_PDF_SUCCESS',
  FETCH_TASK_PDF_ERROR: '@@task/FETCH_TASK_PDF_ERROR',

  FETCH_TASK_OPENED_STORE_START: '@@task/FETCH_TASK_OPENED_STORE_START',
  FETCH_TASK_OPENED_STORE_SUCCESS: '@@task/FETCH_TASK_OPENED_STORE_SUCCESS',
  FETCH_TASK_OPENED_STORE_ERROR: '@@task/FETCH_TASK_OPENED_STORE_ERROR',
}

export const Report = {
  FETCH_TASK_REPORT_START: '@@report/FETCH_TASK_REPORT_START',
  FETCH_TASK_REPORT_SUCCESS: '@@report/FETCH_TASK_REPORT_SUCCESS',
  FETCH_TASK_REPORT_ERROR: '@@report/FETCH_TASK_REPORT_ERROR',

  FETCH_USER_REPORTS_START: '@@report/FETCH_USER_REPORTS_START',
  FETCH_USER_REPORTS_SUCCESS: '@@report/FETCH_USER_REPORTS_SUCCESS',
  FETCH_USER_REPORTS_ERROR: '@@report/FETCH_USER_REPORTS_ERROR',

  FETCH_USER_REPORT_START: '@@report/FETCH_USER_REPORT_START',
  FETCH_USER_REPORT_SUCCESS: '@@report/FETCH_USER_REPORT_SUCCESS',
  FETCH_USER_REPORT_ERROR: '@@report/FETCH_USER_REPORT_ERROR',

  DELTE_REPORT_START: '@@report/DELTE_REPORT_START',
  DELTE_REPORT_SUCCESS: '@@report/DELTE_REPORT_SUCCESS',
  DELTE_REPORT_ERROR: '@@report/DELTE_REPORT_ERROR',

  DOWNLOAD_PDF_START: '@@pdf/DOWNLOAD_PDF_START',
  DOWNLOAD_PDF_SUCCESS: '@@pdf/DOWNLOAD_PDF_SUCCESS',
  DOWNLOAD_PDF_ERROR: '@@pdf/DOWNLOAD_PDF_ERROR'
}

export const OpenedStore = {
  FETCH_OPENED_STORE_START: '@@opened-store/FETCH_OPENED_STORE_START',
  FETCH_OPENED_STORE_SUCCESS: '@@opened-store/FETCH_OPENED_STORE_SUCCESS',
  FETCH_OPENED_STORE_ERROR: '@@opened-store/FETCH_OPENED_STORE_ERROR',
}


export const OpenedStoreList = {
  FETCH_OPENED_STORE_LIST_START: '@@opened-store/FETCH_OPENED_STORE_LIST_START',
  FETCH_OPENED_STORE_LIST_SUCCESS: '@@opened-store/FETCH_OPENED_STORE_LIST_SUCCESS',
  FETCH_OPENED_STORE_LIST_ERROR: '@@opened-store/FETCH_OPENED_STORE_LIST_ERROR',
}

export const OnlineOrder = {
  FETCH_ONLINE_ORDER_START: '@@online-order/FETCH_ONLINE_ORDER_START',
  FETCH_ONLINE_ORDER_SUCCESS: '@@online-order/FETCH_ONLINE_ORDER_SUCCESS',
  FETCH_ONLINE_ORDER_ERROR: '@@online-order/FETCH_ONLINE_ORDER_ERROR',
}

export const IntentionStore = {
  FETCH_INTENTION_STORE_START: '@@intention-store/FETCH_INTENTION_STORE_START',
  FETCH_INTENTION_STORE_SUCCESS: '@@intention-store/FETCH_INTENTION_STORE_SUCCESS',
  FETCH_INTENTION_STORE_ERROR: '@@intention-store/FETCH_INTENTION_STORE_ERROR',
}


export const IntentionMapStore = {
  FETCH_INTENTION_STORE_MAP_START: '@@intention-store/FETCH_INTENTION_STORE_MAP_START',
  FETCH_INTENTION_STORE_MAP_SUCCESS: '@@intention-store/FETCH_INTENTION_STORE_MAP_SUCCESS',
  FETCH_INTENTION_STORE_MAP_ERROR: '@@intention-store/FETCH_INTENTION_STORE_MAP_ERROR',
}

export const POI = {
  FETCH_POI_START: '@@poi/FETCH_POI_START',
  FETCH_POI_SUCCESS: '@@poi/FETCH_POI_SUCCESS',
  FETCH_POI_ERROR: '@@poi/FETCH_POI_ERROR',
}

export const BusinessDistrictProfile = {
  FETCH_BUSINESS_DISTRICT_PROFILE_START: '@@business-district-profile/FETCH_BUSINESS_DISTRICT_PROFILE_START',
  FETCH_BUSINESS_DISTRICT_PROFILE_SUCCESS: '@@business-district-profile/FETCH_BUSINESS_DISTRICT_PROFILE_SUCCESS',
  FETCH_BUSINESS_DISTRICT_PROFILE_ERROR: '@@business-district-profile/FETCH_BUSINESS_DISTRICT_PROFILE_ERROR',
}

export const BackgroundTask = {
  TASK_BACKGROUND_PREPARE: '@@task-background/TASK_BACKGROUND_PREPARE',
  TASK_BACKGROUND_START: '@@task-background/TASK_BACKGROUND_START',
  TASK_BACKGROUND_PROGRESS: '@@task-background/TASK_BACKGROUND_PROGRESS',
  TASK_BACKGROUND_SUCCESS: '@@task-background/TASK_BACKGROUND_SUCCESS',
  TASK_BACKGROUND_ERROR: '@@task-background/TASK_BACKGROUND_ERROR',
}

export const CodePush = {
  ACTION_CODE_PUSH_UPDATE_CHEKECK_START: '@@code-push/ACTION_CODE_PUSH_UPDATE_CHEKECK_START',
  ACTION_CODE_PUSH_UPDATE_CHEKECK_SUCCESS: '@@code-push/ACTION_CODE_PUSH_UPDATE_CHEKECK_SUCCESS',
  ACTION_CODE_PUSH_UPDATE_CHEKECK_ERROR: '@@code-push/ACTION_CODE_PUSH_UPDATE_CHEKECK_ERROR',

  ACTION_CODE_PUSH_MISMATCH_VERSION_FOUND: '@@code-push/ACTION_CODE_PUSH_MISMATCH_VERSION_FOUND',

  ACTION_CODE_PUSH_UPDATE_DOWNLOAD_START: '@@code-push/ACTION_CODE_PUSH_UPDATE_DOWNLOAD_START',
  ACTION_CODE_PUSH_UPDATE_DOWNLOAD_PROGRESS: '@@code-push/ACTION_CODE_PUSH_UPDATE_DOWNLOAD_PROGRESS',
  ACTION_CODE_PUSH_UPDATE_DOWNLOAD_SUCCESS: '@@code-push/ACTION_CODE_PUSH_UPDATE_DOWNLOAD_SUCCESS',
  ACTION_CODE_PUSH_UPDATE_DOWNLOAD_ERROR: '@@code-push/ACTION_CODE_PUSH_UPDATE_DOWNLOAD_ERROR'
}

export const ErrorMessage = {
  ACTION_SHOW_EOOR_MESSAGE: '@@error-message/ACTION_SHOW_EOOR_MESSAGE'
}