platform :ios, '9.0'

# The target name is most likely the name of your project.
abstract_target 'CommonPods' do
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/lib/ios'
  pod 'react-native-amap-geolocation', path: '../node_modules/react-native-amap-geolocation/lib/ios'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'react-native-background-upload', :path => '../node_modules/react-native-background-upload'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'RNOpenAppSettings', :path => '../node_modules/react-native-app-settings'

  target 'SmartLocationRN' do
    
  end
  
  target 'SmartLocationRNTest' do
    
  end
end


# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
